# Read the Docs configuration file for Swanki
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build all formats (HTML, PDF, ePub)
formats:
  - pdf
  - epub

# Python configuration
python:
  install:
    # Install documentation dependencies first
    - requirements: docs/requirements.txt
    # Install the package itself in editable mode
    # This will pick up dependencies from pyproject.toml
    - method: pip
      path: .